"""Inicijalna migracija

Revision ID: 465a0ec1c3c6
Revises: 
Create Date: 2022-05-17 16:01:39.764394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465a0ec1c3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite_plant', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['favorite_plant'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'favorite_plant')
    # ### end Alembic commands ###
