"""Prva migra

Revision ID: 77b1c2923a68
Revises: 
Create Date: 2022-05-19 10:32:22.021579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b1c2923a68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jar', 'plant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jar', sa.Column('plant_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
