"""Dodan date_added u class Jar(db.Model)

Revision ID: c4c041849df0
Revises: 
Create Date: 2022-05-20 20:41:15.232792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c041849df0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jar', sa.Column('date_added', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jar', 'date_added')
    # ### end Alembic commands ###
